import type { RepoFile } from '../types';
const OMIT = /(^|\/)(node_modules|\.git|dist|build|coverage|vendor)(\/|$)|(^|\/)(package-lock|yarn\.lock|pnpm-lock|bun\.lockb)$/;
const TEXT = /\.(ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|kt|rb|php|cs|vue|svelte|html|css|scss|json|ya?ml|md|toml|env)$/i;
const lang = (path:string) => ({ts:'TypeScript',tsx:'TypeScript',js:'JavaScript',jsx:'JavaScript',py:'Python',go:'Go',rs:'Rust',java:'Java',vue:'Vue',svelte:'Svelte',json:'JSON',css:'CSS',html:'HTML',md:'Markdown'}[path.split('.').pop()?.toLowerCase() ?? ''] ?? 'Other');
export function parseGithubUrl(value:string) { const match=value.trim().match(/^https?:\/\/(?:www\.)?github\.com\/([^/]+)\/([^/#?]+)(?:\/tree\/([^?#]+?))?\/?(?:[?#].*)?$/i); if(!match) throw new Error('Paste a public GitHub repository URL, for example github.com/owner/repository.'); return {owner:match[1], repo:match[2].replace(/\.git$/,''), branch:match[3]}; }
export async function ingest(url:string, progress:(stage:string, detail:string)=>void):Promise<{identity:{owner:string;repo:string;branch:string;description:string};files:RepoFile[]}> {
 const {owner,repo,branch:requested}=parseGithubUrl(url); const headers={Accept:'application/vnd.github+json'};
 progress('Connecting to repository','Resolving default branch'); const meta=await fetch(`https://api.github.com/repos/${owner}/${repo}`,{headers}); if(!meta.ok) throw new Error(meta.status===404?'Repository was not found or is private.':meta.status===403?'GitHub API is temporarily rate-limited. Please try again shortly.':'GitHub is unavailable.'); const info=await meta.json(); const branch=requested||info.default_branch;
 progress('Inspecting file structure','Reading the repository tree'); const treeRes=await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`,{headers}); if(!treeRes.ok) throw new Error(treeRes.status===403?'GitHub API is temporarily rate-limited. Please try again shortly.':'Could not read the repository tree.'); const tree=(await treeRes.json()).tree as {path:string;type:string;sha:string;size?:number}[];
 const eligible=tree.filter(x=>x.type==='blob'&&!OMIT.test(x.path)&&TEXT.test(x.path)&&(x.size??0)<=350_000).slice(0,420); if(!eligible.length) throw new Error('No supported text source files were found.');
 progress('Reading relevant source','Fetching supported source through GitHub’s content CDN'); let complete=0; const files:RepoFile[]=[]; for(let i=0;i<eligible.length;i+=10){ const batch=eligible.slice(i,i+10); const loaded=await Promise.all(batch.map(async f=>{ const safePath=f.path.split('/').map(encodeURIComponent).join('/'); const r=await fetch(`https://raw.githubusercontent.com/${owner}/${repo}/${encodeURIComponent(branch)}/${safePath}`); if(!r.ok)return null; try{return {path:f.path,sha:f.sha,size:f.size??0,content:await r.text(),language:lang(f.path),kind:/test|spec/i.test(f.path)?'test':/package\.json|config|\.env|\.ya?ml/i.test(f.path)?'config':'source'} as RepoFile;}catch{return null;} })); files.push(...loaded.filter(Boolean) as RepoFile[]); complete+=batch.length; progress('Reading relevant source',`${complete} of ${eligible.length} selected files`); }
 if(!files.length) throw new Error('GitHub did not return readable source files for this repository.');
 return {identity:{owner,repo,branch,description:info.description||''},files};
}
